version: '3.8'
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: sectum-front
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./front:/go/src